### ISSUE TITLE
karma-trx-reporter sometimes crash the browser (chrome)

### ISSUE THREAD

**Issue by hlovdal** [hatchteam/karma-trx-reporter#14]
When running `ng test` and debugging a test that times out, the browser sometimes dies after the test with error like

```
20 02 2018 11:54:43.016:WARN [Chrome 64.0.3282 (Windows 10 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
Chrome 64.0.3282 (Windows 10 0.0.0) ERROR
Chrome 64.0.3282 (Windows 10 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
Chrome 64.0.3282 (Windows 10 0.0.0): Executed 0 of 0 (skipped 28) DISCONNECTED (17.706 secs / 0 secs)
Chrome 64.0.3282 (Windows 10 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
Chrome 64.0.3282 (Windows 10 0.0.0) ERROR
Chrome 64.0.3282 (Windows 10 0.0.0): Executed 0 of 0 (skipped 28) DISCONNECTED (17.706 secs / 0 secs)
20 02 2018 11:54:43.020:ERROR [karma]: Error: Missing attribute value
    at XMLFragment.attribute (D:\git\...\node_modules\karma-trx-reporter\node_modules\xmlbuilder\lib\XMLFragment.js:267:15)
    at XMLFragment.att (D:\git\...\node_modules\karma-trx-reporter\node_modules\xmlbuilder\lib\XMLFragment.js:377:19)
    at TRXReporter.onBrowserComplete (D:\git\...\node_modules\karma-trx-reporter\index.js:103:18)
    at Server.<anonymous> (D:\git\...\node_modules\karma\lib\events.js:13:22)
    at emitOne (events.js:121:20)
    at Server.emit (events.js:211:7)
    at Timeout._onTimeout (D:\git\...\node_modules\karma\lib\browser.js:51:15)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

I am not sure what triggers this, but I guess that something about the test timing out makes causes karma to have having something missing that karma-trx-reporter depends on. I assume it could be reproduced with a simple test:

```
it('should timeout since done is never called', (done) => {
]);
```

**Comment by brtx** [comment]
Looks like result.total is null in this case, which is not a valid xml attribute value. To me it looks like Karma does not provide us a proper result structure in this case when the test times out. However the error occurs in the onBrowserComplete handler, which is a bit odd anyway for handling the whole test run, as there seems to be a onRunComplete handler as well, which would make more sense to handle the test run results. So in that handler Karma may provide more useful information. See here also: https://www.ironsrc.com/news/how-to-create-a-custom-karma-reporter-3/ I think back in the days when we wrote this plugin, the interface wasn't very well documented, or may have been different so we just used what we found. I think in general Karma should handle timeouts and provide a proper test result, however it may be the case also it doesn't, in that case we could be a bit more defensive using the results. However I would start checking the other handlers for this case first, as I am not quite sure how exactly Karma handles this.

Having said all that, we are not actively working on this plugin anymore. However the code should be quite simple to understand, so if you want you can have a look into it and open a PR proposing a fix and we'll happily merge it for you and publish an updated version on NPM. Sorry for this issue.
